void positive_or_negative();
int _isupper(int c);
int _isdigit(int c);
int mul(int x, int y);
void print_numbers(void);
int _putchar(char c);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int x);
void print_diagonal(int n);
