#!/bin/bash                                                                                                                
git add .                                                                                                                  
echo -e 'Enter commit message below: '
read msg
git commit -m '$msg ....Update'                                                                                         
git push   
