#!/bin/bash                                                                                                                
git add .                                                                                                                  
echo -e 'Enter commit message below\n'
read msg
git commit -m '$msg ....Update'                                                                                         
git push   
