#!/bin/bash
#!/bin/bash                                                                                                                
git add .                                                                                                                  
echo "Enter commit message beloe\n"
read msg
git commit -m "$msg ....Update"                                                                                         
git push   
